# Generated by Django 4.2.6 on 2023-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storywriting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(default='Terror', max_length=200),
            preserve_default=False,
        ),
    ]
